name: VoicechatUtilities
version: ${version}
main: gg.jos.voicechatplugin.VoicechatUtilities
api-version: ${bukkit_api_version}
authors: [ "Jos" ]
description: Voicechat Utilities for the 4Year SMP
depend: [ voicechat ]